algo = str(input('Diga algo:'))
print('O tipo primitivo de {}, é: '.format(algo), type(algo))
print('Só tem espaços?', algo.isspace())
print('É um número?', algo.isnumeric())
print('É alfabetico?', algo.isalpha())
print('É alfanumerico?', algo.isalnum())
print('Está em maiusculo?', algo.isupper())
print('Está em minusculo?', algo.islower())
print('Está captalizado?', algo.istitle())
